name: Delete branch after PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && github.ref != 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch after merge (except develop)
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}
          exclude: develop,master
